Added nginx reverse proxy example
petnet-independence-project/petnet-feeder-service pull request #29
Opened 2020-10-30 16:54 UTC by fbretmounet

2020-10-30 18:09 UTC, kruton requested changes

2020-10-30 18:09 UTC, kruton commented on README.md
> +...
You can use Markdown for this. Replace ... with \`\`\`sh and at the end replace ... with \`\`\`
```suggestion
```bash
```

2020-10-30 18:09 UTC, kruton commented on README.md
> +...
````suggestion
```
````

2020-10-30 18:09 UTC, kruton commented on README.md
> +
````suggestion
```nginx
````

2020-10-30 18:09 UTC, kruton commented on README.md
> +
````suggestion
```
````

2020-10-30 18:09 UTC, kruton commented on README.md
> +        location / {
Indentation is too great here.
```suggestion
    location / {
```

2020-10-30 18:09 UTC, kruton commented on README.md
> +
```suggestion
```

2020-10-30 18:09 UTC, kruton commented on README.md
> +        }
Indentation too great here.

```suggestion
    }
```

2020-10-30 18:09 UTC, kruton commented on README.md
> +The SSL service is required and will need to listen on 443 and reverse proxy back to the docker container service on port 5000.
Above this we mention the IPTables issue, but then this says you must listen on 443. Perhaps this should be broken out into a `docs/` subdirectory where we discuss individual scenarios.

2020-10-30 22:39 UTC, mbillow commented
I am fine with this being in the README for now but we really should start breaking this content up into the GitHub Wiki. I just went and enabled it for the project and will start setting it up.

2020-11-02 17:56 UTC, closed without merging

2020-11-02 17:57 UTC, fbretmounet commented
No longer needed based on adding native support for https.