MQTT: add auth and topic filtering
petnet-independence-project/petnet-feeder-service pull request #33
Opened 2020-11-03 06:20 UTC by kruton

Petnet devices will get a unique API key with which they will log into
the MQTT broker. The Petnet devices will also only be able to subscribe
to the topics of their own gateway IDs.

The server has its own login that is generated whenever the server
starts up. That login can subscribe to any topic in order for it to
respond to all feeders.

Currently there appears to be no way to filter what topics can be
published by a client.

2020-11-03 06:20 UTC, kruton commented
@mbillow Feel free to blow this away and put in your own change. I just uploaded this in case it covers something you didn't do.

2020-11-03 14:52 UTC, mbillow requested changes
@kruton This is really great. I think the only difference in our changes is that I was generating a secret key as well and had a separate table for storing API creds. I doubt we will ever need the secret keys since it is only used in their request signing process. 

Also, the extra credit of topic filtering is a great idea. You’ve earned yourself a gold star! 😂

2020-11-03 14:52 UTC, mbillow commented on feeder/util/mqtt/authentication.py
> +    def __init__(self, context):
You shouldn’t need this constructor. I know they have it in the library code, but a child class will just inherit its parent constructor, so there is no need to make our own if all we are doing is calling super.

2020-11-03 14:52 UTC, mbillow commented on feeder/util/mqtt/authentication.py
> +    @asyncio.coroutine
This wrapper is also redundant (I think 🤔)... Using async def is just the >Python 3.4 syntactic sugar for an async coroutine.

2020-11-03 14:52 UTC, mbillow commented on feeder/util/mqtt/client.py
> +        await self.connect("mqtt://%s:%s@localhost:1883/" % (local_username, local_password))
You can just use a format string here: `f"mqtt://{local_username}:{local_password}@localhost:1883/`

I’ve always found them about 100x easier to grok when trying to understand code.

2020-11-03 14:52 UTC, mbillow commented on feeder/util/mqtt/topic.py
> +    def __init__(self, context):
Same comments here I left on the auth plugin.

2020-11-03 14:56 UTC, mbillow commented on feeder/util/mqtt/topic.py
> +        self.context.logger.debug('username: %s, topic: %s' %
Oh, you should also be passing your logging variables directly to the logger call along with the format string. This lets the logging module handle the substitution.

E.g. `info(“some message %s with %s”, var1, var2)`

2020-11-04 22:40 UTC, mbillow approved these changes

2020-11-04 22:40 UTC, merged